package com.example.com.englishai.backend.application.admin;
import com.example.com.englishai.backend.infrastructure.persistence.entity.*; import com.example.com.englishai.backend.infrastructure.persistence.repository.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.time.*; import java.util.*;
@Service public class CatalogService {
 private final PredefinedAvatarJpaRepository avatars; private final ScenarioDefinitionJpaRepository scenarios; public CatalogService(PredefinedAvatarJpaRepository a,ScenarioDefinitionJpaRepository s){avatars=a;scenarios=s;}
 public List<PredefinedAvatarEntity> publicAvatars(){return avatars.findByEnabledTrueOrderBySortOrderAsc().stream().filter(a->a.getAvatarKey()!=null&&a.getAvatarKey().matches("avatar_[0-9]+" )).toList();} public List<PredefinedAvatarEntity> allAvatars(){return avatars.findAll();}
 @Transactional public PredefinedAvatarEntity saveAvatar(UUID id,String key,String name,String asset,boolean enabled,int order){var now=OffsetDateTime.now(ZoneOffset.UTC);if(id==null&&avatars.existsByAvatarKey(key))throw new IllegalArgumentException("Duplicate avatar key");var e=id==null?new PredefinedAvatarEntity(UUID.randomUUID(),key,name,asset,enabled,order,now):avatars.findById(id).orElseThrow();if(id!=null)e.update(name,asset,enabled,order,now);return avatars.saveAndFlush(e);}
 @Transactional public void disableAvatar(UUID id){avatars.findById(id).orElseThrow().disable(OffsetDateTime.now(ZoneOffset.UTC));}
 public List<ConversationScenarioDefinitionEntity> publicScenarios(){return scenarios.findByEnabledTrueOrderBySortOrderAsc();} public List<ConversationScenarioDefinitionEntity> allScenarios(){return scenarios.findAll();}
 public ConversationScenarioDefinitionEntity requireScenario(String key,boolean active){var e=scenarios.findByScenarioKey(key).orElseThrow(()->new NoSuchElementException("Scenario not found"));if(active&&!e.isEnabled())throw new IllegalStateException("Scenario disabled");return e;}
 @Transactional public ConversationScenarioDefinitionEntity saveScenario(UUID id,String key,String display,String desc,String assistant,String avatar,String behavior,boolean enabled,int order){var now=OffsetDateTime.now(ZoneOffset.UTC);if(id==null&&scenarios.existsByScenarioKey(key))throw new IllegalArgumentException("Duplicate scenario key");if(!avatars.existsByAvatarKey(avatar))throw new IllegalArgumentException("Invalid assistant avatar");var e=id==null?new ConversationScenarioDefinitionEntity(UUID.randomUUID(),key,display,desc,assistant,avatar,behavior,enabled,order,now):scenarios.findById(id).orElseThrow();if(id!=null)e.update(display,desc,assistant,avatar,behavior,enabled,order,now);return scenarios.save(e);}
 @Transactional public void disableScenario(UUID id){scenarios.findById(id).orElseThrow().disable(OffsetDateTime.now(ZoneOffset.UTC));}
}
