package com.example.com.englishai.backend.presentation.rest.profile;
import com.example.com.englishai.backend.application.admin.CatalogService; import com.example.com.englishai.backend.application.profile.*; import jakarta.validation.Valid; import jakarta.validation.constraints.*; import org.springframework.security.core.annotation.AuthenticationPrincipal; import org.springframework.web.bind.annotation.*; import java.time.OffsetDateTime; import java.util.UUID;
@RestController @RequestMapping("/api/v1/users/me/profile") public class ProfileController {
 private final ProfileService service; private final CatalogService catalog; public ProfileController(ProfileService service,CatalogService catalog){this.service=service;this.catalog=catalog;}
 @GetMapping public ProfileResponse get(@AuthenticationPrincipal UUID userId){return ProfileResponse.from(service.get(userId));}
 @PutMapping public ProfileResponse update(@AuthenticationPrincipal UUID userId,@Valid @RequestBody ProfileRequest r){return ProfileResponse.from(service.update(userId,r.preferredName(),r.age(),r.englishLevel(),r.learningGoal()));}
 @PutMapping("/avatar/predefined") public ProfileResponse predefined(@AuthenticationPrincipal UUID userId,@Valid @RequestBody PredefinedAvatar r){if(catalog.publicAvatars().stream().noneMatch(a->a.getAvatarKey().equals(r.avatarKey()))) throw new InvalidProfileRequestException("Invalid avatar");return ProfileResponse.from(service.setAvatar(userId,AvatarType.PREDEFINED,r.avatarKey()));}
 public record PredefinedAvatar(@NotBlank String avatarKey){} public record ProfileRequest(@Size(max=100) String preferredName,@Min(13) @Max(120) Integer age,EnglishLevel englishLevel,LearningGoal learningGoal){}
 public record ProfileResponse(String preferredName,Integer age,EnglishLevel englishLevel,LearningGoal learningGoal,AvatarType avatarType,String avatarKey,boolean onboardingCompleted,OffsetDateTime createdAt,OffsetDateTime updatedAt){static ProfileResponse from(com.example.com.englishai.backend.infrastructure.persistence.entity.UserProfileEntity p){return p==null?new ProfileResponse(null,null,null,null,AvatarType.PREDEFINED,"avatar_default",false,null,null):new ProfileResponse(p.getPreferredName(),p.getAge(),p.getEnglishLevel(),p.getLearningGoal(),AvatarType.PREDEFINED,p.getAvatarKey(),p.isOnboardingCompleted(),p.getCreatedAt(),p.getUpdatedAt());}}
}
