const BACKEND_URL=window.ENGLISHAI_BACKEND_URL||"http://localhost:8080";
const GOOGLE_CLIENT_ID="491728559092-frggmogjfh3mmh0kkduuk11053lucfp3.apps.googleusercontent.com",ACCESS_KEY="englishai_admin_access_token",REFRESH_KEY="englishai_admin_refresh_token";
const $=id=>document.getElementById(id); const loginView=$("login-view"),adminView=$("admin-view"),loginStatus=$("login-status"),status=$("status"); let refreshPromise=null,adminRole=null,avatarRows=[],scenarioRows=[];
const tokens=()=>({access:sessionStorage.getItem(ACCESS_KEY),refresh:sessionStorage.getItem(REFRESH_KEY)}); const saveTokens=d=>{if(d?.accessToken&&d?.refreshToken){sessionStorage.setItem(ACCESS_KEY,d.accessToken);sessionStorage.setItem(REFRESH_KEY,d.refreshToken);}}; const clearTokens=()=>{sessionStorage.removeItem(ACCESS_KEY);sessionStorage.removeItem(REFRESH_KEY);adminRole=null;};
async function raw(path,options={}){const headers={...(options.headers||{})};if(options.body!==undefined&&!headers["Content-Type"]&&!(typeof FormData!=="undefined"&&options.body instanceof FormData))headers["Content-Type"]="application/json";const response=await fetch(BACKEND_URL+path,{...options,headers});let body=null;try{body=await response.json();}catch(_){}return{response,body};}
async function refresh(){if(refreshPromise)return refreshPromise;const t=tokens().refresh;if(!t)return false;refreshPromise=raw("/api/v1/auth/refresh",{method:"POST",body:JSON.stringify({refreshToken:t})}).then(r=>{if(!r.response.ok){clearTokens();return false;}saveTokens(r.body);return true;}).catch(()=>false).finally(()=>refreshPromise=null);return refreshPromise;}
async function api(path,options={},retry=true){let r;try{r=await raw(path,{...options,headers:{...(options.headers||{}),Authorization:`Bearer ${tokens().access||""}`}});}catch(_){return{networkError:true};}if(r.response.status===401&&retry&&await refresh())return api(path,options,false);return r;}
const esc=v=>String(v??"").replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c])); const msg=r=>r?.networkError?"Não foi possível conectar ao servidor.":r?.response?.status===401?"Sua sessão expirou. Entre novamente.":r?.response?.status===403?"Acesso negado.":"Não foi possível concluir a operação.";
function showLogin(text=""){loginView.hidden=false;adminView.hidden=true;loginStatus.textContent=text;$("users-nav").hidden=true;} function showAdmin(){loginView.hidden=true;adminView.hidden=false;}
async function validateAdmin(){const t=tokens();if(!t.access&&!t.refresh)return showLogin();const me=await api("/api/v1/users/me");if(!me.response?.ok){clearTokens();return showLogin(me.networkError?"Não foi possível conectar ao servidor.":"Sua sessão expirou. Entre novamente.");}adminRole=me.body?.role||null;const d=await api("/api/v1/admin/dashboard");if(d.response?.status===403){clearTokens();return showLogin("Você não possui permissão para acessar a área administrativa.");}if(!d.response?.ok)return showLogin(msg(d));showAdmin();$("users-nav").hidden=adminRole!=="SUPER_ADMIN";$("dashboard").replaceChildren(...Object.entries(d.body||{}).map(([k,v])=>{const e=document.createElement("div");e.className="card";e.innerHTML=`<strong>${esc(v)}</strong><span>${esc(k)}</span>`;return e;}));await view("avatars");}
async function view(kind){status.textContent="Carregando...";if(kind==="users"&&adminRole!=="SUPER_ADMIN")return;const path=kind==="avatars"?"/api/v1/admin/avatars":kind==="scenarios"?"/api/v1/admin/conversation-scenarios":"/api/v1/admin/users";const r=await api(path);if(!r.response?.ok){status.textContent=msg(r);return;}if(kind==="avatars"){avatarRows=r.body||[];renderAvatars();}else if(kind==="scenarios"){scenarioRows=(r.body||[]).map(s=>({...s,assistantDisplayName:avatarRows.find(a=>a.key===s.assistantAvatarKey)?.displayName||s.assistantDisplayName}));renderScenarios();}else renderUsers(r.body||[]);status.textContent="";}
const imageUrl=a=>a.imageUrl?`${BACKEND_URL}${a.imageUrl}?v=${encodeURIComponent(a.updatedAt||Date.now())}`:"";
function renderAvatars(){const rows=avatarRows.map(a=>`<tr><td><img class="avatar-thumb" src="${esc(imageUrl(a))}" alt="${esc(a.displayName)}"></td><td>${esc(a.displayName)}</td><td>${esc(a.key)}</td><td>${a.enabled?"Ativo":"Inativo"}</td><td>${esc(a.sortOrder)}</td><td><button data-edit-avatar="${esc(a.id)}">Editar</button> <button data-toggle-avatar="${esc(a.id)}">${a.enabled?"Desativar":"Ativar"}</button></td></tr>`).join("");$("content").innerHTML=`<div class="toolbar"><h2>Avatares</h2><button id="new-avatar">+ Novo avatar</button></div><div class="card"><table><thead><tr><th>Imagem</th><th>Nome</th><th>Key</th><th>Status</th><th>Ordem</th><th>Ações</th></tr></thead><tbody>${rows||"<tr><td colspan=6>Nenhum avatar encontrado.</td></tr>"}</tbody></table></div>`;$("new-avatar").onclick=()=>avatarForm();document.querySelectorAll(".avatar-thumb").forEach(img=>img.addEventListener("error",()=>{const fallback=document.createElement("span");fallback.className="avatar-fallback";fallback.textContent="AI";fallback.title="Imagem indisponível";img.replaceWith(fallback)},{once:true}));document.querySelectorAll("[data-edit-avatar]").forEach(b=>b.onclick=()=>avatarForm(avatarRows.find(x=>x.id===b.dataset.editAvatar)));document.querySelectorAll("[data-toggle-avatar]").forEach(b=>b.onclick=()=>toggleAvatar(avatarRows.find(x=>x.id===b.dataset.toggleAvatar)));}
function renderScenarios(){const rows=scenarioRows.map(s=>{const avatar=avatarRows.find(a=>a.key===s.assistantAvatarKey)||{};return `<tr><td>${s.enabled?"Ativo":"Inativo"}</td><td>${esc(s.displayName)}</td><td>${esc(s.key)}</td><td>${esc(avatar.displayName||s.assistantDisplayName)}</td><td><img class="avatar-thumb" src="${esc(imageUrl(avatar))}" alt="Avatar do assistant"></td><td>${esc(s.sortOrder)}</td><td><button data-edit-scenario="${esc(s.id)}">Editar</button> <button data-toggle-scenario="${esc(s.id)}">${s.enabled?"Desativar":"Ativar"}</button></td></tr>`}).join("");$("content").innerHTML=`<div class="toolbar"><h2>Cenários</h2><button id="new-scenario">+ Novo cenário</button></div><div class="card"><table><thead><tr><th>Status</th><th>Nome</th><th>Key</th><th>Assistant</th><th>Avatar</th><th>Ordem</th><th>Ações</th></tr></thead><tbody>${rows||"<tr><td colspan=7>Nenhum cenário encontrado.</td></tr>"}</tbody></table></div>`;$("new-scenario").onclick=()=>scenarioForm();document.querySelectorAll("[data-edit-scenario]").forEach(b=>b.onclick=()=>scenarioForm(scenarioRows.find(x=>x.id===b.dataset.editScenario)));document.querySelectorAll("[data-toggle-scenario]").forEach(b=>b.onclick=()=>toggleScenario(scenarioRows.find(x=>x.id===b.dataset.toggleScenario)));}
function renderUsers(rows){
 const body=rows.map(u=>{const action=u.role==="USER"?`<button data-role-user="${esc(u.id)}" data-role="ADMIN">Tornar ADMIN</button>`:u.role==="ADMIN"?`<button data-role-user="${esc(u.id)}" data-role="USER">Tornar USER</button>`:"Conta principal";return `<tr><td>${esc(u.preferredName||u.username||"")}</td><td>${esc(u.email)}</td><td>${esc(u.role)}</td><td>${action}</td></tr>`;}).join("");
 $("content").innerHTML=`<div class="toolbar"><h2>Usuários</h2><input id="user-search" type="search" placeholder="Buscar por nome ou email" aria-label="Buscar usuários"></div><div class="card"><table><thead><tr><th>Nome</th><th>Email</th><th>Role</th><th>Ação</th></tr></thead><tbody>${body||"<tr><td colspan=4>Nenhum usuário encontrado.</td></tr>"}</tbody></table></div>`;
 $("user-search").oninput=e=>loadUsers(e.target.value);document.querySelectorAll("[data-role-user]").forEach(b=>b.onclick=()=>changeRole(b));
}
async function loadUsers(search=""){const path=search?`/api/v1/admin/users?search=${encodeURIComponent(search)}`:"/api/v1/admin/users";const r=await api(path);if(r.response?.ok)renderUsers(r.body||[]);else status.textContent=msg(r);}
async function changeRole(button){const role=button.dataset.role;if(!window.confirm(role==="ADMIN"?"Tornar este usuário administrador?":"Remover permissões administrativas deste usuário?"))return;button.disabled=true;const r=await api(`/api/v1/admin/users/${button.dataset.roleUser}/role`,{method:"PATCH",body:JSON.stringify({role})});if(!r.response?.ok){status.textContent=msg(r);button.disabled=false;return;}status.textContent="Role atualizada com sucesso.";await loadUsers($("user-search")?.value||"");}
function modal(title,body,submit){const wrap=document.createElement("div");wrap.className="modal-backdrop";wrap.innerHTML=`<div class="modal" role="dialog" aria-modal="true"><button class="modal-close" aria-label="Fechar">x</button><h2>${title}</h2>${body}</div>`;document.body.append(wrap);const fileInput=wrap.querySelector('input[type="file"]'),preview=wrap.querySelector("#avatar-preview");if(fileInput&&preview){fileInput.addEventListener("change",()=>{if(wrap.previewUrl)URL.revokeObjectURL(wrap.previewUrl);const file=fileInput.files?.[0];if(!file){preview.hidden=true;return;}wrap.previewUrl=URL.createObjectURL(file);preview.src=wrap.previewUrl;preview.hidden=false;});}const close=()=>{if(wrap.previewUrl)URL.revokeObjectURL(wrap.previewUrl);wrap.remove();};wrap.querySelector(".modal-close").onclick=close;wrap.addEventListener("keydown",e=>{if(e.key==="Escape")close();});wrap.querySelector("form").onsubmit=async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;await submit(new FormData(e.target),wrap,b);};wrap.querySelector("input,textarea,select")?.focus();return wrap;}
function avatarForm(a){const editing=!!a;modal(editing?"Editar avatar":"Novo avatar",`<form><label>Key<input name="key" pattern="[A-Za-z0-9_\-]{1,64}" value="${esc(a?.key)}" ${editing?"readonly":"required"}></label><label>Nome<input name="displayName" maxlength="100" value="${esc(a?.displayName)}" required></label><label>Ordem<input name="sortOrder" type="number" value="${a?.sortOrder||0}"></label><label>Imagem${editing?" (opcional para edição)":""}<input name="file" type="file" accept="image/jpeg,image/png,image/webp" ${editing?"":"required"}></label><img id="avatar-preview" class="avatar-preview" alt="Pré-visualização da imagem" hidden><label><input name="enabled" type="checkbox" ${a?.enabled!==false?"checked":""}> Ativo</label><button type="submit">Salvar</button></form>`,async(fd,w,b)=>{status.textContent="Salvando...";let r;if(!editing||fd.get("file")?.size){const data=new FormData();data.append("key",fd.get("key"));data.append("displayName",fd.get("displayName"));data.append("sortOrder",fd.get("sortOrder")||"0");data.append("enabled",fd.get("enabled")?"true":"false");if(fd.get("file")?.size)data.append("file",fd.get("file"));r=await api(editing?`/api/v1/admin/avatars/${a.id}/upload`:"/api/v1/admin/avatars/upload",{method:editing?"PUT":"POST",body:data,headers:{}});}else{r=await api(`/api/v1/admin/avatars/${a.id}`,{method:"PUT",body:JSON.stringify({key:a.key,displayName:fd.get("displayName"),assetKey:a.assetKey,enabled:!!fd.get("enabled"),sortOrder:Number(fd.get("sortOrder")||0)})});}if(!r.response?.ok){status.textContent=msg(r);b.disabled=false;return;}if(w.previewUrl)URL.revokeObjectURL(w.previewUrl);w.remove();status.textContent="Avatar salvo com sucesso.";await view("avatars");});}
async function toggleAvatar(a){if(!a||!window.confirm(`${a.enabled?"Desativar":"Ativar"} este avatar?`))return;const r=a.enabled?await api(`/api/v1/admin/avatars/${a.id}`,{method:"DELETE"}):await api(`/api/v1/admin/avatars/${a.id}`,{method:"PUT",body:JSON.stringify({key:a.key,displayName:a.displayName,assetKey:a.assetKey,enabled:true,sortOrder:a.sortOrder})});status.textContent=r.response?.ok?"Avatar atualizado.":msg(r);await view("avatars");}
async function scenarioForm(s){
 const editing=!!s;
 const catalog=await api("/api/v1/admin/tts/voices");
 const voices=catalog.response?.ok&&Array.isArray(catalog.body)?catalog.body:[];
 const options=avatarRows.map(a=>`<option value="${esc(a.key)}" ${a.key===s?.assistantAvatarKey?"selected":""}>${esc(a.displayName)} (${esc(a.key)})</option>`).join("");
 const selectedVoice=s?.ttsVoice||"";
 const voiceOptions=voices.map(v=>`<option value="${esc(v.key)}" ${v.key===selectedVoice?"selected":""}>${esc(v.displayName)} — ${esc(v.language.toUpperCase())}</option>`).join("");
 const unavailable=selectedVoice&&!voices.some(v=>v.key===selectedVoice)?`<option value="${esc(selectedVoice)}" selected>Voz configurada (indisponível no catálogo)</option>`:"";
 const rate=Number(s?.speechRate??1);
 const wrap=modal(editing?"Editar cenário":"Novo cenário",`<form><label>Key<input name="key" pattern="[A-Z][A-Z0-9_]{2,63}" value="${esc(s?.key)}" ${editing?"readonly":"required"}></label><label>Nome<input name="displayName" maxlength="120" value="${esc(s?.displayName)}" required></label><label>Descrição<textarea name="description" maxlength="500" required>${esc(s?.description)}</textarea></label><label>Nome do assistant<input name="assistantDisplayName" maxlength="120" value="${esc(s?.assistantDisplayName)}" required></label><label>Avatar do assistant<select name="assistantAvatarKey" required>${options}</select></label>
 <label>Voz<select name="ttsVoice"><option value="" ${!selectedVoice?"selected":""}>Padrão do idioma</option>${voiceOptions}${unavailable}</select></label>
 <small>A voz escolhida é usada no idioma indicado; no outro idioma, usa-se a voz padrão correspondente.</small>
 ${!catalog.response?.ok?'<p role="status">Catálogo de vozes indisponível. A configuração atual será preservada.</p>':""}
 <label for="scenario-speech-rate">Velocidade da fala <output id="scenario-speech-rate-value" for="scenario-speech-rate">${rate.toFixed(2)}x</output></label>
 <input id="scenario-speech-rate" name="speechRate" type="range" min="0.75" max="1.25" step="0.01" value="${rate}">
 <label>Behavior instructions <small>(máx. 4000 caracteres)</small><textarea name="behaviorInstructions" maxlength="4000" required>${esc(s?.behaviorInstructions)}</textarea></label><label>Ordem<input name="sortOrder" type="number" value="${s?.sortOrder||0}"></label><label><input name="enabled" type="checkbox" ${s?.enabled!==false?"checked":""}> Ativo</label><button type="submit">Salvar</button></form>`,async(fd,w,b)=>{
  const body={key:fd.get("key"),displayName:fd.get("displayName"),description:fd.get("description"),assistantDisplayName:fd.get("assistantDisplayName"),assistantAvatarKey:fd.get("assistantAvatarKey"),ttsVoice:fd.get("ttsVoice"),speechRate:Number(fd.get("speechRate")),behaviorInstructions:fd.get("behaviorInstructions"),sortOrder:Number(fd.get("sortOrder")||0),enabled:!!fd.get("enabled")};
  const r=await api(editing?`/api/v1/admin/conversation-scenarios/${s.id}`:"/api/v1/admin/conversation-scenarios",{method:editing?"PUT":"POST",body:JSON.stringify(body)});
  if(!r.response?.ok){status.textContent=msg(r);b.disabled=false;return;}w.remove();status.textContent="Cenário salvo com sucesso.";await view("scenarios");
 });
 wrap.querySelector("#scenario-speech-rate").addEventListener("input",event=>{wrap.querySelector("#scenario-speech-rate-value").textContent=Number(event.target.value).toFixed(2)+"x";});
}
async function toggleScenario(s){if(!s||!window.confirm(`${s.enabled?"Desativar":"Ativar"} este cenário?`))return;const body={key:s.key,displayName:s.displayName,description:s.description,assistantDisplayName:s.assistantDisplayName,assistantAvatarKey:s.assistantAvatarKey,behaviorInstructions:s.behaviorInstructions,ttsVoice:s.ttsVoice||"",speechRate:s.speechRate??1,sortOrder:s.sortOrder,enabled:!s.enabled};const r=await api(`/api/v1/admin/conversation-scenarios/${s.id}`,{method:"PUT",body:JSON.stringify(body)});status.textContent=r.response?.ok?"Cenário atualizado.":msg(r);await view("scenarios");}
$("login-form").addEventListener("submit",async e=>{e.preventDefault();const b=$("login-button");b.disabled=true;loginStatus.textContent="Entrando...";try{const r=await raw("/api/v1/auth/login",{method:"POST",body:JSON.stringify({email:$("email").value,password:$("password").value})});if(!r.response.ok){loginStatus.textContent=r.response.status===401?"Email ou senha inválidos.":"Não foi possível entrar.";return;}saveTokens(r.body);await validateAdmin();}catch(_){loginStatus.textContent="Não foi possível conectar ao servidor.";}finally{b.disabled=false;}});$("logout").onclick=async()=>{const t=tokens().refresh;try{if(t)await raw("/api/v1/auth/logout",{method:"POST",body:JSON.stringify({refreshToken:t})});}finally{clearTokens();showLogin();}};document.querySelectorAll("[data-view]").forEach(b=>b.onclick=()=>view(b.dataset.view));
async function prepareGoogle(){if(!window.google?.accounts?.id)return;try{const n=await raw("/api/v1/auth/google/nonce",{method:"POST"});if(!n.response.ok)throw Error();const nonce=n.body.nonce;google.accounts.id.initialize({client_id:GOOGLE_CLIENT_ID,nonce,callback:async c=>{try{const r=await raw("/api/v1/auth/google",{method:"POST",body:JSON.stringify({credential:c.credential,nonce})});if(!r.response.ok){loginStatus.textContent="Não foi possível entrar com Google.";return;}saveTokens(r.body);await validateAdmin();}catch(_){loginStatus.textContent="Não foi possível conectar ao servidor.";}}});google.accounts.id.renderButton($("google-button"),{theme:"outline",size:"large",width:280});}catch(_){loginStatus.textContent="Login com Google indisponível.";}}
const gs=document.createElement("script");gs.src="https://accounts.google.com/gsi/client";gs.async=true;gs.onload=prepareGoogle;document.head.appendChild(gs);validateAdmin();
