package com.example.com.englishai.backend.presentation.rest.admin;
import com.example.com.englishai.backend.application.admin.CatalogService; import com.example.com.englishai.backend.infrastructure.persistence.entity.*; import com.example.com.englishai.backend.application.profile.ProfileImageStorage; import jakarta.validation.Valid; import jakarta.validation.constraints.*; import org.springframework.http.*; import org.springframework.web.bind.annotation.*; import java.time.OffsetDateTime; import java.util.*;
@RestController @RequestMapping("/api/v1/admin") public class AdminCatalogController { private final CatalogService s; private final ProfileImageStorage storage; public AdminCatalogController(CatalogService s,ProfileImageStorage storage){this.s=s;this.storage=storage;}
 @GetMapping("/avatars") public List<Avatar> avatars(){return s.allAvatars().stream().map(Avatar::from).toList();}
 @PostMapping("/avatars") public ResponseEntity<Avatar> createAvatar(@Valid @RequestBody AvatarRequest r){return ResponseEntity.status(201).body(Avatar.from(s.saveAvatar(null,r.key(),r.displayName(),r.assetKey(),r.enabled(),r.sortOrder())));}
 @PostMapping(value="/avatars/upload",consumes=MediaType.MULTIPART_FORM_DATA_VALUE) public ResponseEntity<Avatar> uploadAvatar(@RequestParam String key,@RequestParam String displayName,@RequestParam(defaultValue="true") boolean enabled,@RequestParam(defaultValue="0") int sortOrder,@RequestPart("file") org.springframework.web.multipart.MultipartFile file){if(key==null||!key.matches("[A-Za-z0-9_-]{1,64}")||displayName==null||displayName.isBlank()||file==null||file.isEmpty()||file.getSize()>5*1024*1024)throw new IllegalArgumentException("Invalid avatar image");String type=java.util.Optional.ofNullable(file.getContentType()).orElse("").toLowerCase(java.util.Locale.ROOT);if(!java.util.Set.of("image/jpeg","image/png","image/webp").contains(type))throw new IllegalArgumentException("Invalid avatar image");try{byte[] bytes=file.getBytes();if(!signature(type,bytes))throw new IllegalArgumentException("Invalid avatar image");String asset=storage.store(bytes,type);try{return ResponseEntity.status(201).body(Avatar.from(s.saveAvatar(null,key,displayName,asset,enabled,sortOrder)));}catch(RuntimeException ex){storage.delete(asset);throw ex;}}catch(java.io.IOException ex){throw new IllegalArgumentException("Invalid avatar image");}}
 @PutMapping(value="/avatars/{id}/upload",consumes=MediaType.MULTIPART_FORM_DATA_VALUE) public Avatar replaceAvatarImage(@PathVariable UUID id,@RequestParam String displayName,@RequestParam(defaultValue="true") boolean enabled,@RequestParam(defaultValue="0") int sortOrder,@RequestPart("file") org.springframework.web.multipart.MultipartFile file){if(file==null||file.isEmpty()||file.getSize()>5*1024*1024)throw new IllegalArgumentException("Invalid avatar image");String type=java.util.Optional.ofNullable(file.getContentType()).orElse("").toLowerCase(java.util.Locale.ROOT);if(!java.util.Set.of("image/jpeg","image/png","image/webp").contains(type))throw new IllegalArgumentException("Invalid avatar image");try{byte[] bytes=file.getBytes();if(!signature(type,bytes))throw new IllegalArgumentException("Invalid avatar image");var old=s.allAvatars().stream().filter(a->a.getId().equals(id)).findFirst().orElseThrow();String oldAsset=old.getAssetKey();String asset=storage.store(bytes,type);try{var updated=s.saveAvatar(id,old.getAvatarKey(),displayName,asset,enabled,sortOrder);boolean shared=s.allAvatars().stream().anyMatch(a->!a.getId().equals(id)&&oldAsset.equals(a.getAssetKey()));if(!shared){try{storage.delete(oldAsset);}catch(RuntimeException cleanupFailure){System.err.println("AVATAR_IMAGE_REPLACE status=old_file_cleanup_failed");}}return Avatar.from(updated);}catch(RuntimeException ex){try{storage.delete(asset);}catch(RuntimeException ignored){}throw ex;}}catch(java.io.IOException ex){throw new IllegalArgumentException("Invalid avatar image");}}
 @PutMapping("/avatars/{id}") public Avatar updateAvatar(@PathVariable UUID id,@Valid @RequestBody AvatarRequest r){return Avatar.from(s.saveAvatar(id,r.key(),r.displayName(),r.assetKey(),r.enabled(),r.sortOrder()));}
 @DeleteMapping("/avatars/{id}") @ResponseStatus(HttpStatus.NO_CONTENT) public void disableAvatar(@PathVariable UUID id){s.disableAvatar(id);}
 @GetMapping("/conversation-scenarios") public List<Scenario> scenarios(){return s.allScenarios().stream().map(Scenario::from).toList();}
 @PostMapping("/conversation-scenarios") public ResponseEntity<Scenario> createScenario(@Valid @RequestBody ScenarioRequest r){return ResponseEntity.status(201).body(Scenario.from(s.saveScenario(null,r.key(),r.displayName(),r.description(),r.assistantDisplayName(),r.assistantAvatarKey(),r.behaviorInstructions(),r.enabled(),r.sortOrder(),r.ttsVoice(),r.speechRate())));}
 @PutMapping("/conversation-scenarios/{id}") public Scenario updateScenario(@PathVariable UUID id,@Valid @RequestBody ScenarioRequest r){return Scenario.from(s.saveScenario(id,r.key(),r.displayName(),r.description(),r.assistantDisplayName(),r.assistantAvatarKey(),r.behaviorInstructions(),r.enabled(),r.sortOrder(),r.ttsVoice(),r.speechRate()));}
 @DeleteMapping("/conversation-scenarios/{id}") @ResponseStatus(HttpStatus.NO_CONTENT) public void disableScenario(@PathVariable UUID id){s.disableScenario(id);}
 private static boolean signature(String t,byte[] b){return (t.equals("image/jpeg")&&b.length>3&&(b[0]&255)==255&&(b[1]&255)==216)||(t.equals("image/png")&&b.length>8&&b[0]==(byte)137&&b[1]==80&&b[2]==78&&b[3]==71)||(t.equals("image/webp")&&b.length>12&&b[0]=='R'&&b[1]=='I'&&b[2]=='F'&&b[3]=='F'&&b[8]=='W'&&b[9]=='E'&&b[10]=='B'&&b[11]=='P');}
 public record AvatarRequest(@NotBlank @Pattern(regexp="[A-Za-z0-9_-]{1,64}") String key,@NotBlank @Size(max=100) String displayName,@NotBlank @Size(max=128) String assetKey,boolean enabled,int sortOrder){}
 public record Avatar(UUID id,String key,String displayName,String assetKey,String imageUrl,boolean enabled,int sortOrder,OffsetDateTime createdAt,OffsetDateTime updatedAt){static Avatar from(PredefinedAvatarEntity e){return new Avatar(e.getId(),e.getAvatarKey(),e.getDisplayName(),e.getAssetKey(),"/api/v1/avatars/"+e.getAvatarKey()+"/image",e.isEnabled(),e.getSortOrder(),e.getCreatedAt(),e.getUpdatedAt());}}
 public record ScenarioRequest(@NotBlank @Pattern(regexp="[A-Z][A-Z0-9_]{2,63}") String key,@NotBlank @Size(max=120) String displayName,@NotBlank @Size(max=500) String description,@NotBlank @Size(max=120) String assistantDisplayName,@NotBlank @Size(max=64) String assistantAvatarKey,@NotBlank @Size(max=4000) String behaviorInstructions,boolean enabled,int sortOrder,@Pattern(regexp="[A-Za-z0-9_-]{0,128}") String ttsVoice,@DecimalMin("0.75") @DecimalMax("1.25") Double speechRate){}
 public record Scenario(UUID id,String key,String displayName,String description,String assistantDisplayName,String assistantAvatarKey,String behaviorInstructions,boolean enabled,int sortOrder,String ttsVoice,double speechRate,OffsetDateTime createdAt,OffsetDateTime updatedAt){static Scenario from(ConversationScenarioDefinitionEntity e){return new Scenario(e.getId(),e.getScenarioKey(),e.getDisplayName(),e.getDescription(),e.getAssistantDisplayName(),e.getAssistantAvatarKey(),e.getBehaviorInstructions(),e.isEnabled(),e.getSortOrder(),e.getTtsVoice(),e.getSpeechRate(),e.getCreatedAt(),e.getUpdatedAt());}}
}
