package com.example.com.englishai.backend.presentation.rest.conversation;
import com.example.com.englishai.backend.application.conversation.*; import com.example.com.englishai.backend.application.catalog.AssistantIdentityResolver; import com.example.com.englishai.backend.infrastructure.persistence.entity.*; import com.example.com.englishai.backend.infrastructure.persistence.repository.ScenarioDefinitionJpaRepository; import jakarta.validation.Valid; import jakarta.validation.constraints.*; import org.springframework.http.*; import org.springframework.security.core.annotation.AuthenticationPrincipal; import org.springframework.web.bind.annotation.*; import java.time.OffsetDateTime; import java.util.*;
import org.springframework.web.servlet.mvc.method.annotation.SseEmitter; import java.util.concurrent.CompletableFuture;
@RestController("persistentConversationController") @RequestMapping("/api/v1/conversations") public class ConversationController {
 private final ConversationService service; private final ScenarioDefinitionJpaRepository definitions; private final AssistantIdentityResolver identities; public ConversationController(ConversationService service,ScenarioDefinitionJpaRepository definitions,AssistantIdentityResolver identities){this.service=service;this.definitions=definitions;this.identities=identities;}
 @PostMapping public ResponseEntity<ConversationResponse> create(@AuthenticationPrincipal UUID userId,@Valid @RequestBody CreateRequest r){var created=r.difficulty()==null?service.create(userId,r.scenario(),r.language()):service.create(userId,r.scenario(),r.language(),r.difficulty());return ResponseEntity.status(HttpStatus.CREATED).body(response(created));}
 @GetMapping public List<ConversationResponse> list(@AuthenticationPrincipal UUID userId){return service.list(userId).stream().map(this::response).toList();}
 @GetMapping("/{id}") public ConversationDetail get(@AuthenticationPrincipal UUID userId,@PathVariable UUID id){var c=service.require(userId,id);return new ConversationDetail(response(c),service.history(userId,id).stream().map(MessageResponse::from).toList());}
 @DeleteMapping("/{id}") @ResponseStatus(HttpStatus.NO_CONTENT) public void delete(@AuthenticationPrincipal UUID userId,@PathVariable UUID id){service.delete(userId,id);}
 @PostMapping("/{id}/messages") public ChatResponse add(@AuthenticationPrincipal UUID userId,@PathVariable UUID id,@Valid @RequestBody MessageRequest r){var result=service.chat(userId,id,r.message());return new ChatResponse(result.reply(),result.hasCorrection(),result.correctedText());}
 @PostMapping(path="/{id}/messages/stream",produces=MediaType.TEXT_EVENT_STREAM_VALUE) public SseEmitter stream(@AuthenticationPrincipal UUID userId,@PathVariable UUID id,@Valid @RequestBody MessageRequest r){service.require(userId,id);var emitter=new SseEmitter(130_000L);CompletableFuture.runAsync(()->{try{var result=service.stream(userId,id,r.message(),chunk->send(emitter,"token",json(chunk)));send(emitter,"complete",json("{\"hasCorrection\":"+result.hasCorrection()+",\"correctedText\":"+jsonValue(result.correctedText())+"}"));emitter.complete();}catch(Exception e){try{send(emitter,"error",json("{\"message\":\"AI service temporarily unavailable\"}"));}finally{emitter.complete();}}});return emitter;}
 private ConversationResponse response(ConversationEntity c){var definition=definitions.findByScenarioKey(c.getScenarioKey()).orElseThrow(()->new NoSuchElementException("Scenario not found"));return ConversationResponse.from(c,definition,identities.resolve(definition.getAssistantAvatarKey()));}
 private static void send(SseEmitter e,String event,String data){try{e.send(SseEmitter.event().name(event).data(data));}catch(Exception ex){throw new RuntimeException(ex);}}
 private static String json(String text){return "{\"text\":"+jsonValue(text)+"}";}
 private static String jsonValue(String value){if(value==null)return "null";return "\""+value.replace("\\","\\\\").replace("\"","\\\"").replace("\n","\\n").replace("\r","\\r")+"\"";}
 public record CreateRequest(@NotBlank @Pattern(regexp="[A-Z][A-Z0-9_]{2,63}") String scenario,@NotBlank @Pattern(regexp="(?i)pt|en") String language,@Pattern(regexp="(?i)BEGINNER|INTERMEDIATE|ADVANCED") String difficulty){}
 public record MessageRequest(@NotBlank @Size(max=5000) String message){}
 public record ChatResponse(String reply,boolean hasCorrection,String correctedText){}
 public record ConversationResponse(UUID id,String scenario,String language,String difficulty,String title,String scenarioDisplayName,String description,String assistantDisplayName,String assistantAvatarKey,String assistantAvatarImageUrl,OffsetDateTime createdAt,OffsetDateTime updatedAt){static ConversationResponse from(ConversationEntity c,ConversationScenarioDefinitionEntity d,AssistantIdentityResolver.AssistantIdentity identity){if(d==null || !Objects.equals(c.getScenarioKey(),d.getScenarioKey()))throw new NoSuchElementException("Scenario not found");return new ConversationResponse(c.getId(),c.getScenarioKey(),c.getLanguage(),c.getDifficulty().name(),c.getTitle(),d.getDisplayName(),d.getDescription(),identity.displayName(),identity.avatarKey(),identity.imageUrl(),c.getCreatedAt(),c.getUpdatedAt());}}

 public record ConversationDetail(ConversationResponse conversation,List<MessageResponse> messages){}
 public record MessageResponse(UUID id,String role,String content,String correctedText,OffsetDateTime createdAt){static MessageResponse from(ConversationMessageEntity m){return new MessageResponse(m.getId(),m.getRole(),m.getContent(),m.getCorrectedText(),m.getCreatedAt());}}
}
